### PR TITLE
Steering committee application for Daniel Collins, CSIRO

### PR DESCRIPTION
**Pull request by DC23**

### CODE REVIEW

**Comment by manodeep** [comment]
@DC23 Sorry could you pull in the recent changes from master and update your PR?

@mpfl Pinging to let you know about Daniel's nomination

**Comment by DC23** [comment]
@manodeep Done.

**Comment by manodeep** [comment]
@DC23 Many thanks!

@mpfl Please let me know if this is okay to merge in.

**Comment by manodeep** [comment]
Thanks @mpfl

**Pull request merged**
